// Generated by CoffeeScript 1.6.2
module.exports = {
  setModuleSettings: function(t) {
    t.evaluate = /\[\[([\s\S]+?\]?)\]\]/g;
    t.interpolate = /\[\[=([\s\S]+?)\]\]/g;
    t.encode = /\[\[!([\s\S]+?)\]\]/g;
    t.use = /\[\[#([\s\S]+?)\]\]/g;
    t.useParams = /(^|[^\w$])def(?:\.|\[[\'\"])([\w$\.]+)(?:[\'\"]\])?\s*\:\s*([\w$\.]+|\"[^\"]+\"|\'[^\']+\'|\[[^\]]+\])/g;
    t.define = /\[\[##\s*([\w\.$]+)\s*(\:|=)([\s\S]+?)#\]\]/g;
    t.defineParams = /^\s*([\w$]+):([\s\S]+)/;
    t.conditional = /\[\[\?(\?)?\s*([\s\S]*?)\s*\]\]/g;
    return t.iterate = /\[\[~\s*(?:\]\]|([\s\S]+?)\s*\:\s*([\w$]+)\s*(?:\:\s*([\w$]+))?\s*\]\])/g;
  },
  setFileSettings: function(t) {
    t.evaluate = /\{\{([\s\S]+?\}?)\}\}/g;
    t.interpolate = /\{\{=([\s\S]+?)\}\}/g;
    t.encode = /\{\{!([\s\S]+?)\}\}/g;
    t.use = /\{\{#([\s\S]+?)\}\}/g;
    t.useParams = /(^|[^\w$])def(?:\.|\[[\'\"])([\w$\.]+)(?:[\'\"]\])?\s*\:\s*([\w$\.]+|\"[^\"]+\"|\'[^\']+\'|\{[^\}]+\})/g;
    t.define = /\{\{##\s*([\w\.$]+)\s*(\:|=)([\s\S]+?)#\}\}/g;
    t.defineParams = /^\s*([\w$]+):([\s\S]+)/;
    t.conditional = /\{\{\?(\?)?\s*([\s\S]*?)\s*\}\}/g;
    return t.iterate = /\{\{~\s*(?:\}\}|([\s\S]+?)\s*\:\s*([\w$]+)\s*(?:\:\s*([\w$]+))?\s*\}\})/g;
  },
  setGeneralConfigFileSettings: function(t) {
    t.evaluate = /\|\|([\s\S]+?\|?)\|\|/g;
    t.interpolate = /\|\|=([\s\S]+?)\|\|/g;
    t.encode = /\|\|!([\s\S]+?)\|\|/g;
    t.use = /\|\|#([\s\S]+?)\|\|/g;
    t.useParams = /(^|[^\w$])def(?:\.|\[[\'\"])([\w$\.]+)(?:[\'\"]\])?\s*\:\s*([\w$\.]+|\"[^\"]+\"|\'[^\']+\'|\|[^\|]+\|)/g;
    t.define = /\|\|##\s*([\w\.$]+)\s*(\:|=)([\s\S]+?)#\|\|/g;
    t.defineParams = /^\s*([\w$]+):([\s\S]+)/;
    t.conditional = /\|\|\?(\?)?\s*([\s\S]*?)\s*\|\|/g;
    return t.iterate = /\|\|~\s*(?:\|\||([\s\S]+?)\s*\:\s*([\w$]+)\s*(?:\:\s*([\w$]+))?\s*\|\|)/g;
  }
};
